
server:
  port: ${PORT}
  
spring:
#  application:
#    name: configserver
  cloud:
    config:
      server:
        git: 
          uri: ${URI}
#          uri: https://github.com/fernando-cadalso/microservice-repo
          search-paths: fornecedor, loja 
          #Path pesquisado no git onde estão salvos os arquivos de configuração.
          